# Editing settings: edit tool, read tool (+ structural summaries), LSP, the bash
# interceptor, bash output handling, the shell minimizer, eval backends, python.
{ lib, helpers }:
let
  inherit (helpers)
    mkOpt
    mkSection
    subType
    num
    ;
  t = lib.types;
in
{
  readLineNumbers = mkOpt t.bool "Prepend line numbers to read tool output by default.";

  edit = mkSection "Edit tool." {
    mode = mkOpt (t.enum [
      "apply_patch"
      "hashline"
      "patch"
      "replace"
    ]) "Edit tool variant.";
    fuzzyMatch = mkOpt t.bool "Accept high-confidence fuzzy matches for whitespace differences.";
    fuzzyThreshold = mkOpt num "Similarity threshold for fuzzy matches.";
    streamingAbort = mkOpt t.bool "Abort streaming edit tool calls when patch preview fails.";
    blockAutoGenerated = mkOpt t.bool "Prevent editing of files that appear to be auto-generated.";
  };

  read = mkSection "Read tool." {
    defaultLimit = mkOpt num "Default number of lines returned when read is called without a limit.";
    toolResultPreview = mkOpt t.bool "Render read tool results inline in the transcript instead of summary rows.";
    summarize = mkSection "Structural read summaries." {
      enabled = mkOpt t.bool "Return structural code summaries when read is called without a selector.";
      prose = mkOpt t.bool "Return structural summaries for Markdown and plain text reads.";
      minBodyLines = mkOpt num "Minimum multiline body length before summaries collapse it.";
      minCommentLines = mkOpt num "Minimum block comment length before summaries collapse it.";
      minTotalLines = mkOpt num "Files with fewer total lines are read verbatim.";
      unfoldUntil = mkOpt num "BFS-unfold elidable spans until the summary is at least this many lines.";
      unfoldLimit = mkOpt num "Hard ceiling on summary size while BFS-unfolding.";
    };
  };

  lsp = mkSection "Language Server Protocol tool." {
    enabled = mkOpt t.bool "Enable the lsp tool.";
    formatOnWrite = mkOpt t.bool "Automatically format code files using LSP after writing.";
    diagnosticsOnWrite = mkOpt t.bool "Return LSP diagnostics after writing code files.";
    diagnosticsOnEdit = mkOpt t.bool "Return LSP diagnostics after editing code files.";
    lazy = mkOpt t.bool "Start language servers on first use instead of at session startup.";
    diagnosticsDeduplicate = mkOpt t.bool "Suppress post-edit LSP diagnostics already shown for a file; only surface new or changed ones.";
  };

  bashInterceptor = mkSection "Bash interceptor: block shell commands that have dedicated tools." {
    enabled = mkOpt t.bool "Block shell commands that have dedicated tools.";
    patterns = mkOpt (t.listOf (subType {
      pattern = lib.mkOption {
        type = t.str;
        description = "Regex matched against the command line.";
      };
      tool = lib.mkOption {
        type = t.str;
        description = "Dedicated tool to recommend instead.";
      };
      message = lib.mkOption {
        type = t.str;
        description = "Message shown when the command is blocked.";
      };
      flags = mkOpt t.str "Optional regex flags.";
      allowSubcommands = mkOpt (t.listOf t.str) "Subcommands exempt from the block.";
    })) "Interceptor rules (replaces the built-in defaults entirely when set).";
  };

  bash = mkSection "Bash tool output handling." {
    enabled = mkOpt t.bool "Enable the bash tool for shell command execution.";
    stripTrailingHeadTail = mkOpt t.bool "Silently drop trailing | head / | tail pipes from single-line commands.";
    autoBackground = mkSection "Automatic backgrounding of long-running commands." {
      enabled = mkOpt t.bool "Automatically background long-running bash commands.";
      thresholdMs = mkOpt num "Runtime in ms after which a command is auto-backgrounded.";
    };
  };

  shellMinimizer = mkSection "Shell output minimizer." {
    enabled = mkOpt t.bool "Compress verbose shell output before returning it to the agent.";
    settingsPath = mkOpt t.str "Path to a custom minimizer rules file.";
    only = mkOpt (t.listOf t.str) "Restrict minimization to these command families.";
    except = mkOpt (t.listOf t.str) "Exclude these command families from minimization.";
    maxCaptureBytes = mkOpt num "Maximum bytes captured before minimization.";
    sourceOutlineLevel = mkOpt (t.enum [
      "default"
      "aggressive"
    ]) "Source outline mode for cat/read of source files.";
    legacyFilters = mkOpt t.bool "Use the legacy shell-minimizer filter set.";
  };

  eval = mkSection "Eval tool backends." {
    py = mkOpt t.bool "Allow the eval tool to dispatch to the IPython kernel.";
    js = mkOpt t.bool "Allow the eval tool to dispatch to the in-process JavaScript runtime.";
    jl = mkOpt t.bool "Allow the eval tool to dispatch Julia cells to the persistent Julia kernel.";
    rb = mkOpt t.bool "Allow the eval tool to dispatch Ruby cells to the persistent Ruby kernel.";
  };

  python = mkSection "Python kernel." {
    kernelMode = mkOpt (t.enum [
      "session"
      "per-call"
    ]) "Whether to keep the IPython kernel alive across calls.";
    interpreter = mkOpt t.str "Path to an exact Python executable; disables automatic runtime discovery when set.";
  };

  julia = mkSection "Julia kernel." {
    interpreter = mkOpt t.str "Path to an exact Julia executable; disables automatic runtime discovery when set.";
  };

  ruby = mkSection "Ruby kernel." {
    interpreter = mkOpt t.str "Path to an exact Ruby executable; disables automatic runtime discovery when set.";
  };
}
